server:
  port: 7000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order_routh
          uri: lb://ORDER
          predicates:
            - Path=/*
eureka:
  instance:
    hostname: servicemaster.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceslave.com:8000/eureka/
