server:
  port: 7000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        id: order_routh
        uri: http://127.0.0.1:8080
        predicates:
          - Path=/*
eureka:
  instance:
    hostname: servicemaster.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceslave.com:8000/eureka/
